In [1]:
from others import module

In [3]:
import torch

In [5]:
in_channels = 3
x = torch.randn((100, in_channels, 32, 32))
y = torch.randn((100, in_channels, 32, 32))

In [8]:
loss = torch.nn.MSELoss()

In [9]:
loss(x,y)

tensor(1.9983)

In [10]:
ourloss = module.MSE()

In [11]:
ourloss.forward(x,y)

tensor(613876.0625)

In [4]:
m=torch.nn.Upsample(scale_factor=2, mode='nearest')

In [121]:
def upsample(x, scale):
    y=torch.zeros((1,x.size(1),scale*x.size(2),scale*x.size(3)))
    print (y.shape)
    for i in range (x.size(3)):
        for j in range (x.size(2)):
            for k in range (0,x.size(1)):
                
                y[0,k,j*scale:j*scale+scale,i*scale:i*scale+scale]=x[0,k,j,i]
               
                
    
    
    return y

In [17]:
a=torch.rand((1,1,32,32))

In [18]:
ma=m(a)

In [15]:
b=torch.empty((1,a.size(1),2*a.size(2),2*a.size(3)))

In [14]:
a.size(1)

3

In [16]:
b.shape

torch.Size([1, 3, 64, 64])

In [19]:
ma

tensor([[[[0.0300, 0.9394, 0.8721,  ..., 0.6475, 0.3227, 0.5231],
          [0.7714, 0.9567, 0.8102,  ..., 0.1663, 0.7446, 0.7574],
          [0.1913, 0.1460, 0.5665,  ..., 0.7093, 0.9350, 0.0829],
          ...,
          [0.9828, 0.7579, 0.1483,  ..., 0.7730, 0.0863, 0.1489],
          [0.1247, 0.0711, 0.3300,  ..., 0.2721, 0.1847, 0.5465],
          [0.0240, 0.3565, 0.4091,  ..., 0.5948, 0.2048, 0.9991]]]])

In [23]:
ma[0,0,0:2,0:2]=1

In [24]:
ma

tensor([[[[1.0000, 1.0000, 0.9394,  ..., 0.3227, 0.5231, 0.5231],
          [1.0000, 1.0000, 0.9394,  ..., 0.3227, 0.5231, 0.5231],
          [0.7714, 0.7714, 0.9567,  ..., 0.7446, 0.7574, 0.7574],
          ...,
          [0.1247, 0.1247, 0.0711,  ..., 0.1847, 0.5465, 0.5465],
          [0.0240, 0.0240, 0.3565,  ..., 0.2048, 0.9991, 0.9991],
          [0.0240, 0.0240, 0.3565,  ..., 0.2048, 0.9991, 0.9991]]]])

In [49]:
x=torch.rand((1,1,2,2))

In [106]:
x

tensor([[[[0.5465, 0.5415],
          [0.7915, 0.8045]]]])

In [116]:
upsample(x,2)

torch.Size([1, 1, 4, 4])
(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)


tensor([[[[0.5465, 0.5465, 0.5415, 0.5415],
          [0.5465, 0.5465, 0.5415, 0.5415],
          [0.7915, 0.7915, 0.8045, 0.8045],
          [0.7915, 0.7915, 0.8045, 0.8045]]]])

In [110]:
for i in range (0,x.size(3)):
        for j in range (0,x.size(2)):
            for k in range (0,x.size(1)):
                print((i,j,k))

(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)


In [68]:
y=m(x)

In [45]:
x[0,0,1,1]

tensor(0.0103)

In [48]:
x.size(1)

3

In [73]:
y[0,0,2:4,0:2]

tensor([[0.7915, 0.7915],
        [0.7915, 0.7915]])

In [72]:
y

tensor([[[[0.5465, 0.5465, 0.5415, 0.5415],
          [0.5465, 0.5465, 0.5415, 0.5415],
          [0.7915, 0.7915, 0.8045, 0.8045],
          [0.7915, 0.7915, 0.8045, 0.8045]]]])

In [88]:
y.shape

torch.Size([1, 1, 4, 4])

In [112]:
for i in range (0,x.size(3),1):
        for j in range (0,x.size(2),1):
            for k in range (0,x.size(1)):
                print(y[0,k,2*j:2*j+2,2*i:2*i+2])

tensor([[0.5465, 0.5465],
        [0.5465, 0.5465]])
tensor([[0.7915, 0.7915],
        [0.7915, 0.7915]])
tensor([[0.5415, 0.5415],
        [0.5415, 0.5415]])
tensor([[0.8045, 0.8045],
        [0.8045, 0.8045]])


In [99]:
scale=2

In [118]:
from torch.autograd import Variable

In [131]:
x = Variable(torch.ones(1,1,2,2), requires_grad=True)

In [134]:
y=Variable(2*x,requires_grad=True)
y.backward(torch.ones_like(y))
x.grad

In [133]:
x.grad