In [1]:
import torch
import time

In [4]:
def upsample(x, scale):
    return x.repeat_interleave(scale, dim=2).repeat_interleave(scale, dim=3)

In [92]:
x = torch.arange(100).view(1,1,10,10)

In [93]:
u = upsample(x, 3)

In [95]:
def downsample(y , scale):
    
    
    return ((y[:,:,0::scale,0::scale] ))

tensor([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
          [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
          [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
          [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
          [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]]])


In [82]:
def backward( self , gradwrtoutput ):
    gradwrtinput= downsample(gradwrtoutput,scale)
    return gradwrtinput*scale^2

tensor([[[[0.9723, 0.5200, 0.2680, 0.4789],
          [0.6874, 0.9658, 0.2364, 0.4496],
          [0.1058, 0.0309, 0.5724, 0.2376],
          [0.7705, 0.3477, 0.9755, 0.9305]]]])

TypeError: cumsum() received an invalid combination of arguments - got (), but expected one of:
 * (int dim, *, torch.dtype dtype)
 * (name dim, *, torch.dtype dtype)


120

tensor([[[[0.9723, 0.9723, 0.5200, 0.5200, 0.2680, 0.2680, 0.4789, 0.4789],
          [0.9723, 0.9723, 0.5200, 0.5200, 0.2680, 0.2680, 0.4789, 0.4789],
          [0.6874, 0.6874, 0.9658, 0.9658, 0.2364, 0.2364, 0.4496, 0.4496],
          [0.6874, 0.6874, 0.9658, 0.9658, 0.2364, 0.2364, 0.4496, 0.4496],
          [0.1058, 0.1058, 0.0309, 0.0309, 0.5724, 0.5724, 0.2376, 0.2376],
          [0.1058, 0.1058, 0.0309, 0.0309, 0.5724, 0.5724, 0.2376, 0.2376],
          [0.7705, 0.7705, 0.3477, 0.3477, 0.9755, 0.9755, 0.9305, 0.9305],
          [0.7705, 0.7705, 0.3477, 0.3477, 0.9755, 0.9755, 0.9305, 0.9305]]]])

RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Long instead.

torch.Tensor

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]], dtype=torch.float64)

tensor([[[[ 0,  1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10, 11],
          [12, 13, 14, 15, 16, 17],
          [18, 19, 20, 21, 22, 23],
          [24, 25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34, 35]]]])


tensor([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
          [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
          [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
          [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
          [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]]])

In [97]:
x

tensor([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
          [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
          [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
          [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
          [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]]])

torch.Size([2, 1, 1, 4, 4])

AttributeError: 'Tensor' object has no attribute 'cat'