In [5]:
import torch
import time

In [2]:
1 + 
2

SyntaxError: invalid syntax (<ipython-input-2-64ead37769d2>, line 1)

In [57]:
def upsample(x, scale):
    return x.repeat_interleave(scale, dim=2).repeat_interleave(scale, dim=3)

In [86]:
x = torch.arange(32).view(1,2,4,4).float()

In [87]:
u = upsample(x, 2)

In [111]:
def scuffed_downsample(y , scale):
    acc=torch.zeros(1,-1,y.size(1),int(y.size(2)/scale),int(y.size(3)/scale))
    
    for i in range(scale):
        for j in range(scale):
                acc=torch.cat((acc,y[:,:,j::scale,i::scale].view(1,-1,y.size(1),int(y.size(2)/scale),int(y.size(3)/scale))),dim=0)
           
    
    return acc.sum(dim=0)

In [112]:
d=scuffed_downsample(u,2)

In [113]:
d

tensor([[[[  0.,   4.,   8.,  12.],
          [ 16.,  20.,  24.,  28.],
          [ 32.,  36.,  40.,  44.],
          [ 48.,  52.,  56.,  60.]],

         [[ 64.,  68.,  72.,  76.],
          [ 80.,  84.,  88.,  92.],
          [ 96., 100., 104., 108.],
          [112., 116., 120., 124.]]]])

In [62]:
def backward( self , gradwrtoutput ):
    gradwrtinput= scuffed_downsample(gradwrtoutput,scale)
    return gradwrtinput

In [55]:
acc=torch.zeros(1,1,1,4,4)

TypeError: zeros(): argument 'size' must be tuple of ints, but found element of type float at pos 4

In [54]:
for i in range(2):
    for j in range(2): 
        torch.cat((acc,u[:,:,j::2,i::2].view(1,1,1,4,4)),dim=0 )

In [52]:
u[:,:,0::2,0::2].view(1,1,1,4,4)

tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]]]]])

In [42]:
range(2)

range(0, 2)

In [63]:
d

tensor([[[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.],
          [24., 26., 28., 30.]]]])

In [26]:
(torch.stack([u[:,:,i::3,i::3] for i in range(3)])).shape

torch.Size([3, 1, 1, 10, 10])